### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by ProgramistaZaDyszke** [ThePBone/CscKeystringDecrypt#1]
java -jar CscKeystringDecrypt.jar PLS_keystrings.dat
Exception in thread "main" java.lang.NoClassDefFoundError: Encrypt64
        at Main.main(Main.java:15)
Caused by: java.lang.ClassNotFoundException: Encrypt64
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 1 more

**Comment by timschneeb** [comment]
You need to include Encrypt64.java and SemLog.java when building the JAR as well.

Here's a precompiled JAR:
[CscKeystringDecrypt-1.0-SNAPSHOT-Java11.zip](https://github.com/ThePBone/CscKeystringDecrypt/files/9183530/CscKeystringDecrypt-1.0-SNAPSHOT-Java11.zip)
 
Btw, this repo is probably outdated. I have hard-coded the private key I extracted from my S20+. It may not work with newer models if they use a different key.
